#!/usr/bin/env node
// Generates supabase/seed.sql from docs/channels.yaml:
//   - telemetry.channel_registry rows for every canonical channel
//   - channel set 1 "SDM26-cell-v1": a curated ~40-channel subset at wire
//     rates (1–10 Hz), grouped by equal rate per HTP/1 rules.
//
// channels.yaml is regular enough that we extract the five fields we need
// with line scanning instead of adding a YAML dependency to the workspace.
// If the yaml grows syntax this misses, switch to `pnpm dlx js-yaml`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const yamlPath = join(here, '..', '..', '..', 'docs', 'channels.yaml');
const outPath = join(here, '..', 'supabase', 'seed.sql');

const text = readFileSync(yamlPath, 'utf8');
const channels = [];
let cur = null;
for (const line of text.split(/\r?\n/)) {
  const id = line.match(/^  - id:\s*(\S+)/);
  if (id) {
    cur = { id: id[1] };
    channels.push(cur);
    continue;
  }
  if (!cur) continue;
  const m = line.match(/^    (display_name|units|group|sample_rate_hz):\s*(.*)$/);
  if (m) {
    let v = m[2].trim();
    if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
    cur[m[1]] = v;
  }
}

if (channels.length < 50) {
  throw new Error(`only parsed ${channels.length} channels — yaml drift? check gen-seed.mjs`);
}

const esc = (s) => String(s ?? '').replace(/'/g, "''");

// Curated cellular subset (wire rates, not the 100 Hz log rates). Groups must
// be rate-homogeneous per docs/telemetry-wire-protocol.md. i16fp scale/offset
// chosen so resolution comfortably exceeds sensor noise floors.
const SET1 = {
  // group 0: 10 Hz fast channels
  0: { rate_hz: 10, channels: [
    ['engine.rpm',               'i16fp', 0.5, 0],          // 0.5 rpm res, 0..16383
    ['engine.tps',               'i16fp', 0.01, 0],
    ['engine.aps',               'i16fp', 0.01, 0],
    ['engine.map',               'i16fp', 0.01, 0],
    ['engine.lambda',            'i16fp', 0.0001, 0.6],
    ['engine.gear',              'i16fp', 1, 0],
    ['chassis.steering_angle',   'i16fp', 0.01, 0],
    ['imu.lat_g',                'i16fp', 0.001, 0],
    ['imu.long_g',               'i16fp', 0.001, 0],
    ['imu.vert_g',               'i16fp', 0.001, 0],
    ['imu.yaw_rate',             'i16fp', 0.02, 0],
    ['brake.front_pressure',     'i16fp', 0.5, 0],
    ['brake.rear_pressure',      'i16fp', 0.5, 0],
    ['suspension.travel_fl',     'i16fp', 0.01, 0],
    ['suspension.travel_fr',     'i16fp', 0.01, 0],
    ['suspension.travel_rl',     'i16fp', 0.01, 0],
    ['suspension.travel_rr',     'i16fp', 0.01, 0],
    ['drivetrain.wheel_speed_fl','i16fp', 0.125, 0],
    ['drivetrain.wheel_speed_fr','i16fp', 0.125, 0],
    ['drivetrain.wheel_speed_rl','i16fp', 0.125, 0],
    ['drivetrain.wheel_speed_rr','i16fp', 0.125, 0],
    ['drivetrain.vehicle_speed', 'i16fp', 0.01, 0],
  ]},
  // group 1: 10 Hz GPS (f32 ref+delta pairs per protocol §3.3)
  1: { rate_hz: 10, channels: [
    ['gps.lat_ref', 'f32'], ['gps.lat_d', 'f32'],
    ['gps.lon_ref', 'f32'], ['gps.lon_d', 'f32'],
    ['gps.speed',   'f32'],
  ]},
  // group 2: 1 Hz slow/thermal
  2: { rate_hz: 1, channels: [
    ['engine.water_temp',       'i16fp', 0.01, 0],
    ['engine.oil_temp',         'i16fp', 0.01, 0],
    ['engine.oil_pressure',     'i16fp', 0.05, 0],
    ['engine.fuel_pressure',    'i16fp', 0.05, 0],
    ['engine.battery_voltage',  'i16fp', 0.001, 0],
    ['power.supply_current',    'i16fp', 0.01, 0],
    ['tire.surface_temp_fl',    'i16fp', 0.01, 0],
    ['tire.surface_temp_fr',    'i16fp', 0.01, 0],
    ['tire.surface_temp_rl',    'i16fp', 0.01, 0],
    ['tire.surface_temp_rr',    'i16fp', 0.01, 0],
    ['gps.fix_quality',         'i16fp', 1, 0],
  ]},
};

const lines = [];
lines.push('-- GENERATED by infra/telemetry-supabase/scripts/gen-seed.mjs — do not hand-edit.');
lines.push('');
for (const c of channels) {
  lines.push(
    `insert into telemetry.channel_registry (id, display_name, units, "group", sample_rate_hz) ` +
    `values ('${esc(c.id)}', '${esc(c.display_name)}', '${esc(c.units)}', '${esc(c.group)}', ${Number(c.sample_rate_hz) || 1}) ` +
    `on conflict (id) do update set display_name = excluded.display_name, units = excluded.units, ` +
    `"group" = excluded."group", sample_rate_hz = excluded.sample_rate_hz;`
  );
}
// GPS ref/delta synthetic wire channels (not in channels.yaml — wire-only).
for (const [id, name] of [
  ['gps.lat_ref', 'GPS Lat Reference'], ['gps.lat_d', 'GPS Lat Delta'],
  ['gps.lon_ref', 'GPS Lon Reference'], ['gps.lon_d', 'GPS Lon Delta'],
]) {
  lines.push(
    `insert into telemetry.channel_registry (id, display_name, units, "group", sample_rate_hz) ` +
    `values ('${id}', '${name}', '°', 'GPS', 10) on conflict (id) do nothing;`
  );
}

const def = { groups: {} };
for (const [g, spec] of Object.entries(SET1)) {
  def.groups[g] = {
    rate_hz: spec.rate_hz,
    channels: spec.channels.map(([id, enc, scale, offset]) =>
      enc === 'f32' ? { id, enc } : { id, enc, scale, offset }),
  };
}
lines.push('');
lines.push(
  `insert into telemetry.channel_sets (id, name, car, definition) values ` +
  `(1, 'SDM26-cell-v1', 'SDM26', '${JSON.stringify(def)}'::jsonb) ` +
  `on conflict (id) do update set definition = excluded.definition;`
);
lines.push('');

writeFileSync(outPath, lines.join('\n'));
const total = Object.values(SET1).reduce((n, g) => n + g.channels.length, 0);
console.log(`wrote ${outPath}: ${channels.length + 4} registry rows, channel set 1 (${total} channels, 3 groups)`);
