[package]
name = "helios-csv"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
helios-core = { path = "../helios-core" }
csv = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
arrow = { workspace = true }
