-- Fix LOW finding from ultrareview 2026-05-11:
-- pdm.audit_log.user_id references auth.users(id) with the default ON DELETE
-- RESTRICT, which blocks the Supabase admin API from deleting users that have
-- any audit history. Since the column is already nullable (see
-- 20260507000000_pdm_schema.sql:80), we can safely switch to ON DELETE SET
-- NULL: the audit trail is preserved (action/target_type/target_id/payload all
-- survive) but the user_id is severed so the auth.users row can be removed.
--
-- NOTE: pdm.versions.author_id is NOT NULL and references auth.users(id) with
-- the same default RESTRICT behavior. Switching it to SET NULL requires
-- dropping the NOT NULL — a real schema change with product implications
-- (version history shows "unknown author" after a deletion). That change is
-- deferred for CEO judgment and is intentionally NOT included here.

-- The default FK constraint name generated by Postgres is <table>_<col>_fkey.
do $$
begin
  alter table pdm.audit_log
    drop constraint if exists audit_log_user_id_fkey;
end
$$;

alter table pdm.audit_log
  add constraint audit_log_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete set null;
