-- Finance (Phase B of docs/superpowers/specs/2026-09-28-purchasing-and-finance-design.md)
--
-- The exec ledger: every account (Chase checking, the SAE card, Square, ASU
-- accounts, GoFundMe), every statement line, weekly balances, reimbursements,
-- and the evidence (invoices, order emails) that explains each charge.
--
-- Who sees what:
--   * Execs (finance.view / finance.edit, org-wide) see and edit everything.
--   * Any team member may REQUEST a reimbursement and attach receipts, and
--     sees only their own requests. Nothing else here is visible to them.
--   * Budgets stay per-subteam: purchasing.budget_rows() (redefined below to
--     count spending from the ledger) only returns lines in the caller's scope.
--
-- The counting rule: money counts once, on the statement line where it moved.
-- A card purchase counts on the card; the monthly payment from checking is a
-- transfer. Invoices, order emails and parts-list rows never add money; they
-- are evidence linked to a statement line.
--
-- Amounts are integer cents. Signs on every account: negative = money leaving
-- the team, positive = money arriving. Only the last four digits of a card or
-- account number are ever stored.
--
-- Ids are bigint (not uuid) so that discrepancy keys ("no-invoice:13") are
-- stable and match the ledger this replaces.

create schema if not exists finance;
grant usage on schema finance to authenticated, service_role;

create or replace function finance.can_view()
returns boolean language sql stable security definer set search_path = '' as $$
  select pm.has_capability((select auth.uid()), 'finance.view', null);
$$;
create or replace function finance.can_edit()
returns boolean language sql stable security definer set search_path = '' as $$
  select pm.has_capability((select auth.uid()), 'finance.edit', null);
$$;

-- 1. Tables ------------------------------------------------------------------

create table finance.accounts (
  id                   bigint generated by default as identity primary key,
  name                 text not null unique check (btrim(name) <> ''),
  kind                 text not null check (kind in ('checking', 'credit_card', 'holding', 'university', 'crowdfunding')),
  last4                text check (last4 is null or last4 ~ '^[0-9]{4}$'),
  holder               text,
  credit_limit_cents   bigint check (credit_limit_cents is null or credit_limit_cents >= 0),
  paid_from_account_id bigint references finance.accounts(id),
  project_id           uuid references pm.projects(id),       -- null = shared by both cars
  active               boolean not null default true,
  notes                text not null default '',
  created_at           timestamptz not null default now()
);

create table finance.categories (
  name        text primary key check (btrim(name) <> ''),
  direction   text not null check (direction in ('in', 'out', 'transfer')),
  description text not null default ''
);
insert into finance.categories (name, direction) values
  ('Parts & materials', 'out'), ('Tools & shop supplies', 'out'), ('Software & subscriptions', 'out'),
  ('Shipping & freight', 'out'), ('Vehicle & trailer rental', 'out'), ('Travel: fuel', 'out'),
  ('Travel: lodging', 'out'), ('Travel: food', 'out'), ('Competition & registration', 'out'),
  ('Apparel & merch', 'out'), ('Reimbursement', 'out'), ('Bank fees', 'out'),
  ('Dues', 'in'), ('Donation / sponsorship', 'in'), ('Merch & website sales', 'in'),
  ('Cash deposit', 'in'), ('Refund', 'in'),
  ('Transfer: card payment', 'transfer'), ('Transfer: between accounts', 'transfer'),
  ('Needs category', 'out')
on conflict (name) do nothing;

create table finance.statements (
  id                bigint generated by default as identity primary key,
  account_id        bigint not null references finance.accounts(id),
  period_start      date,
  closing_date      date not null,
  opening_cents     bigint,
  ending_cents      bigint,
  net_charges_cents bigint not null default 0,
  purchases_cents   bigint not null default 0,
  credits_cents     bigint not null default 0,
  source_file       text not null default '',
  sha256            text unique,
  imported_at       timestamptz not null default now()
);

create table finance.transactions (
  id               bigint generated by default as identity primary key,
  account_id       bigint not null references finance.accounts(id),
  date             date not null,            -- the day money moved (a check: the day it was written)
  post_date        date,
  cleared_date     date,                     -- checks: the day it hit the bank; null = outstanding
  amount_cents     bigint not null,
  description      text not null default '',
  vendor           text,
  kind             text not null check (kind in ('charge', 'credit', 'deposit', 'withdrawal', 'check', 'transfer', 'fee')),
  category         text not null default 'Needs category' references finance.categories(name) on update cascade,
  reference        text,
  status           text not null default 'posted' check (status in ('posted', 'expected')),
  transfer_group   text,
  needs_review     boolean not null default false,
  review_note      text not null default '',
  source           text not null default 'manual',
  source_key       text unique,
  statement_id     bigint references finance.statements(id) on delete set null,
  notes            text not null default '',
  allocation_basis text not null default '',
  created_by       uuid default auth.uid(),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index transactions_account_date on finance.transactions (account_id, date);
-- one check number is written once per account (pay_reimbursements checks
-- first; this catches two execs paying at the same moment)
create unique index transactions_manual_check_number on finance.transactions (account_id, reference)
  where kind = 'check' and source = 'manual' and reference is not null;

-- Cost splitting: one or more shares per transaction, summing to its amount.
create table finance.txn_allocations (
  id           bigint generated by default as identity primary key,
  txn_id       bigint not null references finance.transactions(id) on delete cascade,
  project_id   uuid references pm.projects(id),            -- null = whole team
  subteam_id   uuid not null references pm.subteams(id),
  amount_cents bigint not null check (amount_cents >= 0)
);
create index txn_allocations_txn on finance.txn_allocations (txn_id);

-- Invoices and order emails: they describe a purchase but never add money.
create table finance.evidence (
  id           bigint generated by default as identity primary key,
  kind         text not null check (kind in ('invoice', 'email', 'airtable', 'slack')),
  source_file  text not null default '',
  source_key   text unique,
  vendor       text,
  vendor_raw   text,
  order_ref    text,
  date         date,
  total_cents  bigint,
  items        text not null default '',
  project_id   uuid references pm.projects(id),
  subteam_id   uuid references pm.subteams(id),
  status       text not null default '',
  ship_to      text not null default '',
  payment_hint text not null default '',
  link         text not null default '',
  record_type  text not null default '',
  flags        jsonb not null default '[]',
  raw          jsonb not null default '{}',
  txn_id       bigint references finance.transactions(id) on delete set null,
  match_method text not null default '',
  match_score  real not null default 0
);
create index evidence_txn on finance.evidence (txn_id);

-- Balances typed in by an exec before the weekly meeting (or read off a
-- statement). Append-only: a correction is a new row, never an edit.
create table finance.balance_entries (
  id              bigint generated by default as identity primary key,
  account_id      bigint not null references finance.accounts(id),
  as_of           date not null,
  balance_cents   bigint not null,
  -- 'balance', or for the SAE card 'available_credit' (what PaymentNet shows)
  measure         text not null default 'balance' check (measure in ('balance', 'available_credit')),
  confirmed       boolean not null default true,
  note            text not null default '',
  entered_by      uuid default auth.uid(),
  entered_by_name text not null default '',
  entered_at      timestamptz not null default now(),
  source_key      text unique
);

-- Money the team owes a person. Members ask ('requested'); an exec checks the
-- receipts ('owed' or 'denied'); it is 'paid' when the check is written.
create table finance.reimbursements (
  id             bigint generated by default as identity primary key,
  person_name    text not null check (btrim(person_name) <> ''),
  user_id        uuid references auth.users(id) on delete set null,   -- set when they asked in Helios
  amount_cents   bigint check (amount_cents is null or amount_cents >= 0),
  reason         text not null default '',
  project_id     uuid references pm.projects(id),
  subteam_id     uuid references pm.subteams(id),
  item_id        uuid references purchasing.items(id) on delete set null,
  requested_date date default purchasing.team_day(),
  status         text not null default 'owed' check (status in ('requested', 'owed', 'paid', 'denied')),
  decided_by     uuid,
  decided_at     timestamptz,
  denied_reason  text not null default '',
  check_number   text,
  check_txn_id   bigint references finance.transactions(id) on delete set null,
  paid_date      date,
  notes          text not null default '',
  source_key     text unique,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index reimbursements_user on finance.reimbursements (user_id);

-- Receipt files live in the private 'receipts' storage bucket at
-- <reimbursement id>/<random>-<file name>.
create table finance.reimbursement_receipts (
  id               bigint generated by default as identity primary key,
  reimbursement_id bigint not null references finance.reimbursements(id) on delete cascade,
  object_path      text not null unique,
  file_name        text not null,
  content_type     text not null default '',
  size_bytes       bigint,
  uploaded_by      uuid default auth.uid(),
  uploaded_at      timestamptz not null default now()
);

-- An exec's "resolved" decision on a discrepancy. Flags are recomputed from
-- the data every time; this is keyed by the flag's stable key.
create table finance.discrepancy_resolutions (
  key              text primary key,
  resolved_by      uuid default auth.uid(),
  resolved_by_name text not null default '',
  resolved_at      timestamptz not null default now(),
  note             text not null default ''
);

-- Audit trail for money that belongs to sponsors and the university.
create table finance.events (
  id        bigint generated always as identity primary key,
  at        timestamptz not null default now(),
  actor_id  uuid,
  entity    text not null,
  entity_id text not null,
  field     text not null,
  old_value text,
  new_value text
);
create index events_entity on finance.events (entity, entity_id);

-- A parts-list item links to the statement line that paid for it.
alter table purchasing.items
  add column finance_txn_id bigint references finance.transactions(id) on delete set null,
  add column match_method   text not null default '';

-- 2. Audit trigger ---------------------------------------------------------------

create or replace function finance.audit()
returns trigger language plpgsql security definer set search_path = '' as $$
declare k text; o jsonb; n jsonb; v_id text;
begin
  if tg_op = 'DELETE' then
    o := to_jsonb(old);
    v_id := coalesce(o ->> 'id', o ->> 'key', o ->> 'name', '');
    insert into finance.events (actor_id, entity, entity_id, field, old_value)
    values ((select auth.uid()), tg_table_name, v_id, '*deleted*', left(o::text, 2000));
    return old;
  end if;
  n := to_jsonb(new);
  v_id := coalesce(n ->> 'id', n ->> 'key', n ->> 'name', '');
  if tg_op = 'INSERT' then
    insert into finance.events (actor_id, entity, entity_id, field, new_value)
    values ((select auth.uid()), tg_table_name, v_id, '*created*', left(n::text, 2000));
    return new;
  end if;
  o := to_jsonb(old);
  for k in select jsonb_object_keys(n) loop
    if k <> 'updated_at' and (o -> k) is distinct from (n -> k) then
      insert into finance.events (actor_id, entity, entity_id, field, old_value, new_value)
      values ((select auth.uid()), tg_table_name, v_id, k, o ->> k, n ->> k);
    end if;
  end loop;
  if n ? 'updated_at' then new.updated_at := now(); end if;
  return new;
end; $$;

do $$
declare t text;
begin
  foreach t in array array['accounts', 'categories', 'transactions', 'txn_allocations', 'evidence',
                            'balance_entries', 'reimbursements', 'reimbursement_receipts',
                            'discrepancy_resolutions'] loop
    execute format('create trigger %1$s_audit_ins after insert on finance.%1$s for each row execute function finance.audit()', t);
    execute format('create trigger %1$s_audit_upd before update on finance.%1$s for each row execute function finance.audit()', t);
    execute format('create trigger %1$s_audit_del after delete on finance.%1$s for each row execute function finance.audit()', t);
  end loop;
end $$;

-- 3. RLS ---------------------------------------------------------------------------

alter table finance.accounts                enable row level security;
alter table finance.categories              enable row level security;
alter table finance.statements              enable row level security;
alter table finance.transactions            enable row level security;
alter table finance.txn_allocations         enable row level security;
alter table finance.evidence                enable row level security;
alter table finance.balance_entries         enable row level security;
alter table finance.reimbursements          enable row level security;
alter table finance.reimbursement_receipts  enable row level security;
alter table finance.discrepancy_resolutions enable row level security;
alter table finance.events                  enable row level security;

-- Exec-only tables: execs read; editors write. Statements only arrive through
-- the importer (service role). Events are written by the trigger.
do $$
declare t text;
begin
  foreach t in array array['accounts', 'categories', 'statements', 'transactions', 'txn_allocations',
                            'evidence', 'balance_entries', 'discrepancy_resolutions', 'events'] loop
    execute format('create policy %1$s_read on finance.%1$s for select to authenticated using (finance.can_view())', t);
  end loop;
  foreach t in array array['accounts', 'categories', 'txn_allocations', 'evidence', 'discrepancy_resolutions'] loop
    execute format('create policy %1$s_insert on finance.%1$s for insert to authenticated with check (finance.can_edit())', t);
    execute format('create policy %1$s_update on finance.%1$s for update to authenticated using (finance.can_edit()) with check (finance.can_edit())', t);
    execute format('create policy %1$s_delete on finance.%1$s for delete to authenticated using (finance.can_edit())', t);
  end loop;
end $$;

create policy transactions_insert on finance.transactions for insert to authenticated
  with check (finance.can_edit());
create policy transactions_update on finance.transactions for update to authenticated
  using (finance.can_edit()) with check (finance.can_edit());
-- Statement lines can be edited or flagged, never deleted; only hand-entered ones can go.
create policy transactions_delete on finance.transactions for delete to authenticated
  using (finance.can_edit() and source = 'manual');

-- Imported lines stay imported: changing `source` would let them be deleted.
create or replace function finance.keep_source()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.source is distinct from old.source or new.source_key is distinct from old.source_key then
    raise exception 'where a statement line came from can''t be changed' using errcode = '42501';
  end if;
  return new;
end; $$;
create trigger transactions_keep_source before update on finance.transactions
  for each row execute function finance.keep_source();

-- Balances are append-only.
create policy balance_entries_insert on finance.balance_entries for insert to authenticated
  with check (finance.can_edit() and entered_by = (select auth.uid()));

-- Reimbursements: execs see all; a member sees their own. Members create and
-- withdraw requests through the RPCs below.
create policy reimbursements_read on finance.reimbursements for select to authenticated
  using (finance.can_view() or user_id = (select auth.uid()));
create policy reimbursements_insert on finance.reimbursements for insert to authenticated
  with check (finance.can_edit());
create policy reimbursements_update on finance.reimbursements for update to authenticated
  using (finance.can_edit()) with check (finance.can_edit());
create policy reimbursements_delete on finance.reimbursements for delete to authenticated
  using (finance.can_edit());

-- Deciding and paying go through decide_reimbursement() and
-- pay_reimbursements(), which check who is deciding. A direct write (the
-- exec's edit form) may fix a name, amount or reason, but can't move a
-- request to owed or paid, and nobody can write to their own request.
create or replace function finance.guard_reimbursement_writes()
returns trigger language plpgsql set search_path = '' as $$
begin
  if current_user <> 'authenticated' then return coalesce(new, old); end if;   -- the RPCs (definer) and the service role
  if tg_op = 'INSERT' then
    if new.user_id = auth.uid() then
      raise exception 'ask for your own reimbursement under Get reimbursed' using errcode = '42501';
    end if;
    if new.status not in ('owed', 'requested') then
      raise exception 'a new reimbursement is owed or requested' using errcode = '42501';
    end if;
    return new;
  end if;
  if old.user_id = auth.uid() then
    raise exception 'another exec has to handle your own reimbursement' using errcode = '42501';
  end if;
  if tg_op = 'UPDATE' and (new.status is distinct from old.status or new.user_id is distinct from old.user_id
      or new.decided_by is distinct from old.decided_by or new.check_txn_id is distinct from old.check_txn_id) then
    raise exception 'approve, decline and pay with the buttons, not by editing the row' using errcode = '42501';
  end if;
  if tg_op = 'UPDATE' and old.status = 'paid' and (new.amount_cents is distinct from old.amount_cents
      or new.paid_date is distinct from old.paid_date or new.check_number is distinct from old.check_number) then
    raise exception 'a paid reimbursement''s amount and check can''t change' using errcode = '42501';
  end if;
  return coalesce(new, old);
end; $$;
create trigger reimbursements_guard before insert or update or delete on finance.reimbursements
  for each row execute function finance.guard_reimbursement_writes();

-- Can the caller read (or, p_write, add/remove) receipts for this reimbursement?
-- Owners may change receipts only while the request is still being reviewed.
create or replace function finance.receipt_access(p_reimbursement bigint, p_write boolean)
returns boolean language sql stable security definer set search_path = '' as $$
  select case when p_write then finance.can_edit() else finance.can_view() end
      or exists (
        select 1 from finance.reimbursements r
        where r.id = p_reimbursement and r.user_id = (select auth.uid())
          and (not p_write or r.status = 'requested'));
$$;

create policy receipts_read on finance.reimbursement_receipts for select to authenticated
  using (finance.receipt_access(reimbursement_id, false));
create policy receipts_insert on finance.reimbursement_receipts for insert to authenticated
  with check (finance.receipt_access(reimbursement_id, true) and uploaded_by = (select auth.uid()));
create policy receipts_delete on finance.reimbursement_receipts for delete to authenticated
  using (finance.receipt_access(reimbursement_id, true));

grant select on all tables in schema finance to authenticated;
grant insert, update, delete on finance.accounts, finance.categories, finance.transactions,
  finance.txn_allocations, finance.evidence, finance.reimbursements, finance.discrepancy_resolutions
  to authenticated;
grant insert, delete on finance.reimbursement_receipts to authenticated;
grant insert on finance.balance_entries to authenticated;
grant usage, select on all sequences in schema finance to authenticated;
grant all on all tables in schema finance to service_role;
grant usage, select on all sequences in schema finance to service_role;

-- 4. Receipt storage -----------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts', 'receipts', false, 10485760,
        array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf'])
on conflict (id) do nothing;

-- Object names are '<reimbursement id>/<file>'.
create or replace function finance.receipt_object_access(p_name text, p_write boolean)
returns boolean language sql stable security definer set search_path = '' as $$
  select case when split_part(p_name, '/', 1) ~ '^[0-9]{1,18}$'
              then finance.receipt_access(split_part(p_name, '/', 1)::bigint, p_write)
              else false end;
$$;

create policy "receipts read" on storage.objects for select to authenticated
  using (bucket_id = 'receipts' and finance.receipt_object_access(name, false));
create policy "receipts upload" on storage.objects for insert to authenticated
  with check (bucket_id = 'receipts' and finance.receipt_object_access(name, true));
create policy "receipts delete" on storage.objects for delete to authenticated
  using (bucket_id = 'receipts' and finance.receipt_object_access(name, true));

-- 5. RPCs ------------------------------------------------------------------------------

-- Any team member asks to be paid back. Execs are told who asked and for what.
create or replace function finance.request_reimbursement(
  p_amount_cents bigint, p_reason text, p_date date default null,
  p_project uuid default null, p_subteam uuid default null, p_item uuid default null)
returns bigint language plpgsql security definer set search_path = '' as $$
declare v_uid uuid := auth.uid(); v_name text; v_id bigint;
begin
  if v_uid is null then raise exception 'authentication required' using errcode = '42501'; end if;
  if not purchasing.is_member() then raise exception 'only team members can ask to be reimbursed' using errcode = '42501'; end if;
  if p_amount_cents is null or p_amount_cents <= 0 then raise exception 'enter the amount you paid' using errcode = '22023'; end if;
  if coalesce(btrim(p_reason), '') = '' then raise exception 'say what it was for' using errcode = '22023'; end if;
  v_name := purchasing.display_name(v_uid);
  insert into finance.reimbursements (person_name, user_id, amount_cents, reason, project_id, subteam_id,
                                      item_id, requested_date, status)
  values (v_name, v_uid, p_amount_cents, left(btrim(p_reason), 500), p_project, p_subteam, p_item,
          coalesce(p_date, purchasing.team_day()), 'requested')
  returning id into v_id;
  perform purchasing.notify(
    array(select u from unnest(purchasing.users_with('finance.edit')) u where u <> v_uid), null, 'reimbursement',
    v_name || ' asked to be reimbursed $' || to_char(p_amount_cents / 100.0, 'FM999999990.00') || ' for '
    || left(btrim(p_reason), 120) || '. Check the receipts in Finance > Reimbursements.');
  return v_id;
end; $$;

-- The requester withdraws a request that hasn't been decided yet. (The app
-- deletes the receipt files first; the owner may while it is 'requested'.)
create or replace function finance.withdraw_reimbursement(p_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
begin
  delete from finance.reimbursements
  where id = p_id and user_id = auth.uid() and status = 'requested';
  if not found then
    raise exception 'only your own request, before an exec has looked at it' using errcode = '42501';
  end if;
end; $$;

-- An exec accepts a request (it becomes money owed) or turns it down.
create or replace function finance.decide_reimbursement(p_id bigint, p_decision text, p_note text default '')
returns void language plpgsql security definer set search_path = '' as $$
declare v finance.reimbursements;
begin
  if not finance.can_edit() then raise exception 'only execs decide reimbursements' using errcode = '42501'; end if;
  if p_decision not in ('approve', 'deny') then raise exception 'decision must be approve or deny' using errcode = '22023'; end if;
  select * into v from finance.reimbursements where id = p_id for update;
  if not found then raise exception 'no such reimbursement' using errcode = 'P0002'; end if;
  if v.status <> 'requested' then raise exception 'that reimbursement was already decided' using errcode = '22023'; end if;
  if v.user_id = auth.uid() then
    raise exception 'another exec has to decide your own reimbursement' using errcode = '42501';
  end if;
  update finance.reimbursements set
    status = case when p_decision = 'approve' then 'owed' else 'denied' end,
    denied_reason = case when p_decision = 'deny' then coalesce(p_note, '') else '' end,
    decided_by = auth.uid(), decided_at = now()
  where id = p_id;
  perform purchasing.notify(array[v.user_id], null, 'reimbursement',
    case when p_decision = 'approve'
      then 'Your reimbursement for ' || left(v.reason, 80) || ' ($' || to_char(coalesce(v.amount_cents, 0) / 100.0, 'FM999999990.00')
           || ') was approved. You''ll be paid by check.'
      else 'Your reimbursement for ' || left(v.reason, 80) || ' was declined' || coalesce(': ' || nullif(p_note, ''), '.') end);
end; $$;

-- Mark reimbursements paid, optionally writing one check for them into the
-- ledger (as an uncashed check on the checking account). One check pays one
-- person.
create or replace function finance.pay_reimbursements(
  p_ids bigint[], p_paid_date date default null, p_check_number text default null, p_add_check boolean default false)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_people int; v_person text; v_total bigint; v_txn bigint; v_checking bigint; v_reasons text;
  v_date date := coalesce(p_paid_date, purchasing.team_day()); v_check text := nullif(btrim(coalesce(p_check_number, '')), '');
begin
  if not finance.can_edit() then raise exception 'only execs pay reimbursements' using errcode = '42501'; end if;
  if coalesce(array_length(p_ids, 1), 0) = 0 then raise exception 'pick at least one' using errcode = '22023'; end if;
  -- lock the rows so two execs paying at once can't both write a check
  perform 1 from finance.reimbursements where id = any (p_ids) for update;
  if (select count(*) from finance.reimbursements where id = any (p_ids)) <> (select count(distinct x) from unnest(p_ids) x) then
    raise exception 'some of those reimbursements don''t exist' using errcode = 'P0002';
  end if;
  if exists (select 1 from finance.reimbursements where id = any (p_ids) and user_id = auth.uid()) then
    raise exception 'another exec has to pay your own reimbursement' using errcode = '42501';
  end if;
  if exists (select 1 from finance.reimbursements where id = any (p_ids) and status in ('requested', 'denied')) then
    raise exception 'approve the requests before paying them' using errcode = '22023';
  end if;
  if exists (select 1 from finance.reimbursements where id = any (p_ids) and status = 'paid') then
    raise exception 'some of those were already paid' using errcode = '22023';
  end if;
  if p_add_check then
    select count(distinct lower(btrim(person_name))), min(person_name), sum(coalesce(amount_cents, 0)),
           string_agg(reason, '; ')
      into v_people, v_person, v_total, v_reasons
      from finance.reimbursements where id = any (p_ids);
    if v_people <> 1 then raise exception 'one check pays one person: pick one person''s rows' using errcode = '22023'; end if;
    if v_check is null then raise exception 'enter the check number' using errcode = '22023'; end if;
    if v_total <= 0 then raise exception 'the amounts are missing' using errcode = '22023'; end if;
    select id into v_checking from finance.accounts where kind = 'checking' and active order by id limit 1;
    if v_checking is null then raise exception 'no checking account' using errcode = 'P0002'; end if;
    if exists (select 1 from finance.transactions where account_id = v_checking and kind = 'check' and reference = v_check) then
      raise exception 'check #% is already in the ledger', v_check using errcode = '23505';
    end if;
    insert into finance.transactions (account_id, date, amount_cents, description, kind, category, reference, source, notes)
    values (v_checking, v_date, -v_total, 'Reimbursement check to ' || v_person || ': ' || left(v_reasons, 300),
            'check', 'Reimbursement', v_check, 'manual', 'Written for ' || array_length(p_ids, 1) || ' reimbursement(s)')
    returning id into v_txn;
  end if;
  update finance.reimbursements set
    status = 'paid', paid_date = coalesce(paid_date, v_date),
    check_number = coalesce(v_check, check_number), check_txn_id = coalesce(v_txn, check_txn_id)
  where id = any (p_ids);
  perform purchasing.notify(
    array(select distinct user_id from finance.reimbursements where id = any (p_ids)), null, 'reimbursement',
    'Your reimbursement was paid' || coalesce(' by check #' || v_check, '') || '.');
  return v_txn;
end; $$;

-- Replace a transaction's split. Shares must add up to the transaction's amount.
-- p_allocations: [{project_id, subteam_id, amount_cents}]
create or replace function finance.set_allocations(p_txn bigint, p_allocations jsonb, p_basis text default 'manual')
returns void language plpgsql security definer set search_path = '' as $$
declare v_amount bigint; v_kind text; v_sum bigint;
begin
  if not finance.can_edit() then raise exception 'only execs edit the ledger' using errcode = '42501'; end if;
  select abs(amount_cents), kind into v_amount, v_kind from finance.transactions where id = p_txn for update;
  if not found then raise exception 'no such transaction' using errcode = 'P0002'; end if;
  if exists (select 1 from jsonb_array_elements(coalesce(p_allocations, '[]')) a where (a ->> 'amount_cents')::bigint < 0) then
    raise exception 'each share is a positive amount' using errcode = '22023';
  end if;
  select coalesce(sum((a ->> 'amount_cents')::bigint), 0) into v_sum from jsonb_array_elements(coalesce(p_allocations, '[]')) a;
  if jsonb_array_length(coalesce(p_allocations, '[]')) > 0 and v_kind <> 'transfer' and v_sum <> v_amount then
    raise exception 'the split must add up to $%; it adds up to $%',
      to_char(v_amount / 100.0, 'FM999999990.00'), to_char(v_sum / 100.0, 'FM999999990.00') using errcode = '22023';
  end if;
  delete from finance.txn_allocations where txn_id = p_txn;
  insert into finance.txn_allocations (txn_id, project_id, subteam_id, amount_cents)
  select p_txn, nullif(a ->> 'project_id', '')::uuid, (a ->> 'subteam_id')::uuid, (a ->> 'amount_cents')::bigint
  from jsonb_array_elements(coalesce(p_allocations, '[]')) a;
  update finance.transactions set allocation_basis = case when jsonb_array_length(coalesce(p_allocations, '[]')) > 0
    then coalesce(p_basis, 'manual') else '' end where id = p_txn;
end; $$;

-- A charge's subteam split, built from the parts linked to it (weighted by
-- each part's cost and its car/subteam percentages). Used while the split
-- is still one Helios made from parts; a split an exec entered is left alone.
create or replace function finance.split_from_parts(p_txn bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare v_amount bigint; v_kind text; v_basis text;
begin
  select abs(amount_cents), kind, allocation_basis into v_amount, v_kind, v_basis from finance.transactions where id = p_txn;
  if not found or v_kind = 'transfer' then return; end if;
  if exists (select 1 from finance.txn_allocations where txn_id = p_txn) and v_basis not like 'from part%' then return; end if;
  delete from finance.txn_allocations where txn_id = p_txn;
  with w as (
    select a.project_id, a.subteam_id, sum(greatest(purchasing.item_cost(i), 1) * a.percent) as weight
    from purchasing.items i join purchasing.item_allocations a on a.item_id = i.id
    where i.finance_txn_id = p_txn
    group by a.project_id, a.subteam_id
  ), r as (
    select project_id, subteam_id, round(v_amount * weight / sum(weight) over ())::bigint as share,
           row_number() over (order by subteam_id, project_id) as n, count(*) over () as cnt
    from w
  )
  insert into finance.txn_allocations (txn_id, project_id, subteam_id, amount_cents)
  select p_txn, project_id, subteam_id,
         case when n = cnt   -- the last share takes the rounding, so the split adds up exactly
              then v_amount - coalesce(sum(share) over (order by n rows between unbounded preceding and 1 preceding), 0)
              else share end
  from r;
  update finance.transactions set allocation_basis = coalesce(
    'from parts ' || (select string_agg(code, ', ' order by code) from purchasing.items where finance_txn_id = p_txn), '')
  where id = p_txn;
end; $$;

-- Link a parts-list item to the statement line that paid for it (null to
-- unlink). A received item that is linked becomes RECONCILED. The charge it
-- leaves and the charge it joins have their parts-based splits rebuilt, so
-- the money counts once, toward the right subteams.
create or replace function finance.link_item(p_item uuid, p_txn bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare v_old bigint;
begin
  if not finance.can_edit() then raise exception 'only execs edit the ledger' using errcode = '42501'; end if;
  select finance_txn_id into v_old from purchasing.items where id = p_item for update;
  if not found then raise exception 'no such item' using errcode = 'P0002'; end if;
  update purchasing.items set
    finance_txn_id = p_txn,
    match_method = case when p_txn is null then 'rejected' else 'manual' end,
    status = case when p_txn is not null and status = 'RECEIVED' then 'RECONCILED'
                  when p_txn is null and status = 'RECONCILED' then 'RECEIVED' else status end,
    reconciled_at = case when p_txn is not null and status = 'RECEIVED' then now() else reconciled_at end
  where id = p_item;
  if v_old is not null and v_old is distinct from p_txn then perform finance.split_from_parts(v_old); end if;
  if p_txn is not null then perform finance.split_from_parts(p_txn); end if;
end; $$;

-- 6. Budgets from the ledger ---------------------------------------------------------------
--
-- Spent     = charges in the ledger, by their split, plus ordered items paid
--             outside the ledger (ASU money, a member's own card)
-- Committed = approved or ordered items whose charge isn't in the ledger yet
-- Planned   = items still "not ready" or "ready to order"
-- Once an item is linked to its statement line it counts through the ledger,
-- never twice. Members only get the lines for their own subteams.

-- Every share of money that counts toward a budget, with what it came from.
-- Internal: only budget_rows() and budget_detail() call it, and they filter
-- by the caller's scope.
create or replace function purchasing.budget_shares(p_season uuid default null)
returns table (
  project_id uuid, subteam_id uuid, bucket text, cents bigint,
  source text, ref text, on_date date, label text, txn_id bigint, item_id uuid)
language sql stable security definer set search_path = '' as $$
  with season as (
    select s.id, s.starts_on, s.ends_on from purchasing.seasons s
    where s.id = coalesce(p_season, (select id from purchasing.seasons where is_current))
  )
  -- parts-list items that aren't in the ledger yet
  select a.project_id, a.subteam_id,
         case
           when i.status in ('PLANNED', 'READY') then 'planned'
           when i.status in ('ORDERED', 'BACKORDERED', 'SHIPPED', 'DELIVERED', 'RECEIVED', 'RECONCILED')
                and (i.paid_by <> '' or i.payment_method ~* '(asu|dean|personal|reimburs|foundation)') then 'spent'
           else 'committed'
         end,
         round(purchasing.item_cost(i) * a.percent / 100.0)::bigint,
         'part', i.code, coalesce(i.ordered_at, purchasing.team_day(i.created_at)), i.title, null::bigint, i.id
  from purchasing.items i
  join purchasing.item_allocations a on a.item_id = i.id
  where i.status not in ('DENIED', 'CANCELLED', 'HAVE')
    and i.finance_txn_id is null
    and (i.season_id is null or i.season_id = (select id from season))
  union all
  -- ledger spending: charges count positive, refunds and card credits negative, transfers never
  select al.project_id, al.subteam_id, 'spent',
         case when t.amount_cents > 0 then -al.amount_cents else al.amount_cents end,
         'ledger', coalesce(t.reference, ''), t.date,
         -- a check's memo can name the person paid back; show only "Check"
         -- (and a withdrawal's, e.g. a Zelle payee): members see only the kind
         coalesce(nullif(t.vendor, ''), case when t.kind in ('check', 'withdrawal') then initcap(t.kind) else t.description end), t.id, null::uuid
  from finance.transactions t
  join finance.txn_allocations al on al.txn_id = t.id
  where t.status = 'posted' and t.kind in ('charge', 'check', 'withdrawal', 'fee', 'credit')
    and ((select starts_on from season) is null or t.date >= (select starts_on from season))
    and ((select ends_on from season) is null or t.date <= (select ends_on from season));
$$;

drop function if exists purchasing.budget_rows(uuid);
create or replace function purchasing.budget_rows(p_season uuid default null)
returns table (
  budget_line_id uuid, project_id uuid, project_code text, name text, subteam_ids uuid[],
  budget_cents bigint, spent_cents bigint, committed_cents bigint, planned_cents bigint)
language sql stable security definer set search_path = '' as $$
  with season as (
    select coalesce(p_season, (select id from purchasing.seasons where is_current)) as id
  ),
  lines as (
    select l.id, l.project_id, l.name, l.amount_cents,
           array_agg(ls.subteam_id) filter (where ls.subteam_id is not null) as subteams
    from purchasing.budget_lines l
    left join purchasing.budget_line_subteams ls on ls.budget_line_id = l.id
    where l.season_id = (select id from season)
    group by l.id
  ),
  line_of as (
    select s.*, (select l.id from lines l
                 where l.project_id is not distinct from s.project_id and s.subteam_id = any (l.subteams) limit 1) as line_id
    from purchasing.budget_shares(p_season) s
  )
  select l.id, l.project_id, p.car_code, l.name, coalesce(l.subteams, '{}'),
         l.amount_cents,
         coalesce(sum(x.cents) filter (where x.bucket = 'spent'), 0)::bigint,
         coalesce(sum(x.cents) filter (where x.bucket = 'committed'), 0)::bigint,
         coalesce(sum(x.cents) filter (where x.bucket = 'planned'), 0)::bigint
  from lines l
  join pm.projects p on p.id = l.project_id
  left join line_of x on x.line_id = l.id
  where purchasing.is_exec()
     or exists (select 1 from unnest(l.subteams) st where pm.has_capability((select auth.uid()), 'purchasing.view', st))
  group by l.id, l.project_id, p.car_code, l.name, l.subteams, l.amount_cents
  union all
  -- spending on a subteam no budget line covers is shown, never dropped
  select null, x.project_id, coalesce(p.car_code, 'Team'), '(no budget line) ' || st.name, array[x.subteam_id], 0,
         coalesce(sum(x.cents) filter (where x.bucket = 'spent'), 0)::bigint,
         coalesce(sum(x.cents) filter (where x.bucket = 'committed'), 0)::bigint,
         coalesce(sum(x.cents) filter (where x.bucket = 'planned'), 0)::bigint
  from line_of x
  left join pm.projects p on p.id = x.project_id
  join pm.subteams st on st.id = x.subteam_id
  where x.line_id is null
    and (purchasing.is_exec() or pm.has_capability((select auth.uid()), 'purchasing.view', x.subteam_id))
  group by x.project_id, p.car_code, st.name, x.subteam_id;
$$;

-- What makes up one budget row: every part and ledger share for that car and
-- those subteams. Members only get their own subteams' shares, and see a
-- charge's vendor, date and amount but never a link into the ledger.
create or replace function purchasing.budget_detail(p_project uuid, p_subteams uuid[], p_season uuid default null)
returns table (bucket text, source text, ref text, on_date date, label text, cents bigint, txn_id bigint, item_id uuid)
language sql stable security definer set search_path = '' as $$
  select s.bucket, s.source, s.ref, s.on_date, s.label, s.cents,
         case when finance.can_view() then s.txn_id end, s.item_id
  from purchasing.budget_shares(p_season) s
  where s.project_id is not distinct from p_project
    and s.subteam_id = any (p_subteams)
    and (purchasing.is_exec() or pm.has_capability((select auth.uid()), 'purchasing.view', s.subteam_id))
  order by case s.bucket when 'spent' then 0 when 'committed' then 1 else 2 end, s.on_date desc nulls last;
$$;

-- 7. Import support ---------------------------------------------------------------------
--
-- The import from the old ledger keeps its ids (so discrepancy keys and the
-- resolutions made there still line up). Afterwards, move every id counter
-- past the imported rows. Service role only.
create or replace function finance.sync_ids()
returns void language plpgsql security definer set search_path = '' as $$
declare t text; v_max bigint;
begin
  foreach t in array array['accounts', 'statements', 'transactions', 'txn_allocations', 'evidence',
                            'balance_entries', 'reimbursements', 'reimbursement_receipts'] loop
    execute format('select max(id) from finance.%I', t) into v_max;
    perform setval(pg_get_serial_sequence('finance.' || t, 'id'), greatest(coalesce(v_max, 0), 1), v_max is not null);
  end loop;
  select max(nullif(regexp_replace(code, '\D', '', 'g'), '')::bigint) into v_max from purchasing.items;
  perform setval('purchasing.item_code_seq', greatest(coalesce(v_max, 0), 1), v_max is not null);
end; $$;

-- 8. Uploads: statements, invoices, Square ---------------------------------------------
--
-- Execs upload CSV exports (Chase checking, Chase card, Square, or any bank
-- CSV with a column mapping) and invoice lists. The app parses and previews
-- them; import_transactions() writes one file atomically. A file can only be
-- imported once (by its sha256), and each line only once (by source_key).

create table finance.imports (
  id          bigint generated by default as identity primary key,
  sha256      text not null unique,
  file_name   text not null,
  format      text not null,
  account_id  bigint references finance.accounts(id),
  rows_added  int not null default 0,
  imported_by uuid default auth.uid(),
  imported_at timestamptz not null default now()
);

-- How a bank description maps to a vendor and a default category, and the
-- spellings the Airtable sheets used ("TPM Breaks" is TBM Brakes). Vendor
-- names aren't financial, so every member can read them (the parts list uses
-- them); only execs change them.
create table finance.vendors (
  name             text primary key check (btrim(name) <> ''),
  aliases          text[] not null default '{}',
  merchant_pattern text not null default '',     -- regex against statement descriptions
  default_category text not null default 'Needs category' references finance.categories(name) on update cascade,
  review_note      text not null default ''
);

-- An invoice or receipt file attached to a ledger line lives in the private
-- 'finance-docs' bucket.
alter table finance.evidence add column object_path text unique;

alter table finance.imports enable row level security;
alter table finance.vendors enable row level security;
create policy imports_read on finance.imports for select to authenticated using (finance.can_view());
create policy vendors_read on finance.vendors for select to authenticated using (purchasing.is_member());
create policy vendors_write on finance.vendors for all to authenticated using (finance.can_edit()) with check (finance.can_edit());
grant select on finance.imports, finance.vendors to authenticated;
grant insert, update, delete on finance.vendors to authenticated;
grant all on finance.imports, finance.vendors to service_role;
grant usage, select on all sequences in schema finance to authenticated, service_role;
create trigger vendors_audit_ins after insert on finance.vendors for each row execute function finance.audit();
create trigger vendors_audit_upd before update on finance.vendors for each row execute function finance.audit();
create trigger vendors_audit_del after delete on finance.vendors for each row execute function finance.audit();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('finance-docs', 'finance-docs', false, 20971520,
        array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf'])
on conflict (id) do nothing;
create policy "finance docs read" on storage.objects for select to authenticated
  using (bucket_id = 'finance-docs' and finance.can_view());
create policy "finance docs upload" on storage.objects for insert to authenticated
  with check (bucket_id = 'finance-docs' and finance.can_edit());
create policy "finance docs delete" on storage.objects for delete to authenticated
  using (bucket_id = 'finance-docs' and finance.can_edit());

-- Write one uploaded file. Execs only.
--   p_file:       {sha256, file_name, format, account_id}
--   p_statement:  optional {account_id, period_start, closing_date, opening_cents,
--                 ending_cents, net_charges_cents, purchases_cents, credits_cents}
--   p_rows:       new transactions (same fields as finance.transactions; lines
--                 whose source_key already exists are skipped)
--   p_clears:     [{txn_id, cleared_date}] checks already in the ledger that cleared
--   p_confirms:   [{transfer_group, date, amount_cents?}] expected transfers (card autopay) that happened
--   p_balances:   [{account_id, as_of, balance_cents, note, source_key}] bank-reported balances
create or replace function finance.import_transactions(
  p_file jsonb, p_statement jsonb default null, p_rows jsonb default '[]', p_clears jsonb default '[]',
  p_confirms jsonb default '[]', p_balances jsonb default '[]')
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_stmt bigint; v_added int := 0; v_n int; v_cleared int := 0; v_confirmed int := 0; v_bal int := 0; r jsonb;
begin
  if not finance.can_edit() then raise exception 'only execs can upload statements' using errcode = '42501'; end if;
  if coalesce(p_file ->> 'sha256', '') = '' then raise exception 'missing file fingerprint' using errcode = '22023'; end if;
  if exists (select 1 from finance.imports where sha256 = p_file ->> 'sha256') then
    raise exception 'that file was already imported' using errcode = '23505';
  end if;

  if p_statement is not null then
    insert into finance.statements (account_id, period_start, closing_date, opening_cents, ending_cents,
                                    net_charges_cents, purchases_cents, credits_cents, source_file, sha256)
    values ((p_statement ->> 'account_id')::bigint, nullif(p_statement ->> 'period_start', '')::date,
            (p_statement ->> 'closing_date')::date, nullif(p_statement ->> 'opening_cents', '')::bigint,
            nullif(p_statement ->> 'ending_cents', '')::bigint, coalesce((p_statement ->> 'net_charges_cents')::bigint, 0),
            coalesce((p_statement ->> 'purchases_cents')::bigint, 0), coalesce((p_statement ->> 'credits_cents')::bigint, 0),
            p_file ->> 'file_name', p_file ->> 'sha256')
    returning id into v_stmt;
  end if;

  for r in select * from jsonb_array_elements(coalesce(p_rows, '[]')) loop
    insert into finance.transactions (account_id, date, post_date, cleared_date, amount_cents, description, vendor,
      kind, category, reference, status, transfer_group, needs_review, review_note, source, source_key, statement_id, notes)
    values ((r ->> 'account_id')::bigint, (r ->> 'date')::date, nullif(r ->> 'post_date', '')::date,
            nullif(r ->> 'cleared_date', '')::date, (r ->> 'amount_cents')::bigint, coalesce(r ->> 'description', ''),
            nullif(r ->> 'vendor', ''), r ->> 'kind', coalesce(nullif(r ->> 'category', ''), 'Needs category'),
            nullif(r ->> 'reference', ''), coalesce(nullif(r ->> 'status', ''), 'posted'), nullif(r ->> 'transfer_group', ''),
            coalesce((r ->> 'needs_review')::boolean, false), coalesce(r ->> 'review_note', ''),
            coalesce(nullif(r ->> 'source', ''), p_file ->> 'format'), r ->> 'source_key',
            case when (r ->> 'account_id')::bigint = (p_statement ->> 'account_id')::bigint then v_stmt end,
            coalesce(r ->> 'notes', ''))
    on conflict (source_key) do nothing;
    get diagnostics v_n = row_count;
    v_added := v_added + v_n;
  end loop;

  for r in select * from jsonb_array_elements(coalesce(p_clears, '[]')) loop
    update finance.transactions set cleared_date = (r ->> 'cleared_date')::date
    where id = (r ->> 'txn_id')::bigint and kind = 'check' and cleared_date is null;
    get diagnostics v_n = row_count;
    v_cleared := v_cleared + v_n;
  end loop;

  for r in select * from jsonb_array_elements(coalesce(p_confirms, '[]')) loop
    -- amount_cents (optional, positive): what was actually paid, when it
    -- differs from what was expected; each side keeps its sign
    update finance.transactions set status = 'posted', date = (r ->> 'date')::date, post_date = (r ->> 'date')::date,
      cleared_date = (r ->> 'date')::date, notes = trim(notes || ' Confirmed by ' || (p_file ->> 'file_name') || '.'),
      amount_cents = case when nullif(r ->> 'amount_cents', '') is null then amount_cents
                          else sign(amount_cents) * abs((r ->> 'amount_cents')::bigint) end
    where transfer_group = r ->> 'transfer_group' and status = 'expected';
    get diagnostics v_n = row_count;
    v_confirmed := v_confirmed + v_n;
  end loop;

  for r in select * from jsonb_array_elements(coalesce(p_balances, '[]')) loop
    insert into finance.balance_entries (account_id, as_of, balance_cents, measure, confirmed, note, entered_by_name, source_key)
    values ((r ->> 'account_id')::bigint, (r ->> 'as_of')::date, (r ->> 'balance_cents')::bigint, 'balance', true,
            coalesce(r ->> 'note', ''), 'Bank export', r ->> 'source_key')
    on conflict (source_key) do nothing;
    get diagnostics v_n = row_count;
    v_bal := v_bal + v_n;
  end loop;

  insert into finance.imports (sha256, file_name, format, account_id, rows_added)
  values (p_file ->> 'sha256', p_file ->> 'file_name', p_file ->> 'format', nullif(p_file ->> 'account_id', '')::bigint, v_added);

  return jsonb_build_object('added', v_added, 'cleared', v_cleared, 'confirmed', v_confirmed, 'balances', v_bal,
                            'statement_id', v_stmt);
end; $$;

revoke all on all functions in schema finance from public, anon;
grant execute on function
  finance.can_view(), finance.can_edit(),
  finance.receipt_access(bigint, boolean), finance.receipt_object_access(text, boolean),
  finance.request_reimbursement(bigint, text, date, uuid, uuid, uuid),
  finance.withdraw_reimbursement(bigint),
  finance.decide_reimbursement(bigint, text, text),
  finance.pay_reimbursements(bigint[], date, text, boolean),
  finance.set_allocations(bigint, jsonb, text),
  finance.link_item(uuid, bigint),
  finance.import_transactions(jsonb, jsonb, jsonb, jsonb, jsonb, jsonb)
to authenticated;
grant execute on all functions in schema finance to service_role;
revoke all on function purchasing.budget_rows(uuid), purchasing.budget_shares(uuid),
  purchasing.budget_detail(uuid, uuid[], uuid) from public, anon;
grant execute on function purchasing.budget_rows(uuid), purchasing.budget_detail(uuid, uuid[], uuid)
  to authenticated, service_role;
grant execute on function purchasing.budget_shares(uuid) to service_role;
